# HOW TO DEPLOY WITH SAM (creates samconfig.toml on first guided deploy):
#   sam build -t template.yaml
#   sam deploy -t template.yaml --guided --profile fas
#
# Create the e11-users table

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core Users table (retained on stack delete)

Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: e11-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI_Email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UsersTableName:
    Value: !Ref UsersTable
    Export:
      Name: !Sub "${AWS::StackName}:UsersTableName"
  UsersTableArn:
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}:UsersTableArn"
