#!/bin/bash
set -euo pipefail
set -v				# enter verbose mode

echo Setting up Ubuntu 24.04 LTS for CSCI E-11

PYTHON=python3.13
echo Install apt items
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt update
sudo apt -y install python3.13 pipx

# Update PATH at the top of the .bashrc file, before the exit for non-interactive shells.
grep -q 'export PATH="\$HOME/.local/bin:\$PATH"' ~/.bashrc || \
    sed -i '1s|^|export PATH="$HOME/.local/bin:$PATH"\n|' ~/.bashrc

source $HOME/.bashrc
pipx install poetry

################################################################
echo Wait for system to complete seeding...
sudo snap wait system seed.loaded
sudo snap install --classic aws-cli

# Give the student a more powerful editor
sudo apt install emacs-gtk
