AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3-to-EventBridge Integration 2 - Existing Buckets

Parameters:
  DynamoTableArn:
    Type: String
    Description: ARN of existing DynamoDB table for class list
  ExistingBucketName:
    Type: String
    Default: cscie-11
  LoggingBucketName:
    Type: String
    Default: cscie-11-s3watcher-logs
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues: [CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET]
    Description: Default LOG_LEVEL environment value for the function

Resources:
  # Bucket for CloudTrail Logs
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LoggingBucketName

  # Bucket policy enables CloudTrail to write to the logging bucket
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt LoggingBucket.Arn
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub ${LoggingBucket.Arn}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  # The CloudTrail trail - uses the LoggingBucketName as the trail name
  myTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: BucketPolicy
    Properties:
      TrailName: !Ref LoggingBucketName
      S3BucketName: !Ref LoggingBucket
      IsLogging: true
      IsMultiRegionTrail: false
      EventSelectors:
        - IncludeManagementEvents: false
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub arn:aws:s3:::${ExistingBucketName}/
      IncludeGlobalServiceEvents: false

  ### This section configures the consuming Lambda function ###

  # Lambda function
  EventConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event_consumer/
      Runtime: python3.12
      Handler: app.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          DDB_TABLE_ARN: !Ref DynamoTableArn
          LOG_LEVEL: !Ref LogLevel            # default; can be overridden per request JSON
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AllowS3Read
              Effect: Allow
              Action:
                - s3:GetObject
              Resource: "arn:aws:s3:::cscie-11/*"

            - Sid: AllowRoute53Changes
              Effect: Allow
              Action:
                - route53:ChangeResourceRecordSets
                - route53:ListResourceRecordSets
                - route53:GetChange
              Resource: "arn:aws:route53:::hostedzone/*"

            - Sid: AllowSES
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"

            - Sid: DynWrite
              Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DescribeTable
              Resource: !Ref DynamoTableArn

  # EventBridge rule - invokes EventConsumerFunction
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: EventRule
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail:
          eventName:
            - PutObject
          requestParameters:
            bucketName:
              - !Ref ExistingBucketName
      Targets:
        - Arn: !GetAtt EventConsumerFunction.Arn
          Id: EventConsumerFunctionTarget

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref EventConsumerFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn
