# HOW TO DEPLOY STAGING WITH SAM:
#   make generate-templates
#   sam build -t template-staging.yaml
#   sam deploy -t template-staging.yaml --guided --profile fas
#     # Answer the prompts; you'll be asked for:
#     #   - Stack Name (e.g., home-app-staging)
#     #   - AWS Region (e.g., us-east-1)
#     #   - Parameters: DynamoTableArn, HostedZoneId
#     #   - (Optional) CertificateArn; leave blank to auto-create one in ACM
#   # On next runs:
#   make generate-templates && sam build -t template-staging.yaml && sam deploy -t template-staging.yaml
#
# Result:
#   - An HTTP API at https://stage.csci-e-11.org/
#   - Routes handled by the Lambda handler in home.py (lambda_handler)
#   - JSON API (POST) for grading; also supports ping/ping-mail actions

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: e11 home Lambda staging environment (stage.csci-e-11.org)

Globals:
  Function:
    Environment:
      Variables:
        LOG_LEVEL: !Ref LogLevel
        DDB_TABLE_ARN: !Ref UsersTableArn          # existing users table
        OIDC_SECRET_ID: !Ref OidcSecretId
        SESSIONS_TABLE_NAME: !Ref SessionsTableName     # new (optional helper)

Parameters:
  UsersTableArn:
    Type: String
    Description: ARN of existing DynamoDB table for grades/logs
  SessionsTableName:
    Type: String
    Description: Name of existing DynamoDB table for sessions
  OidcSecretId:
    Type: String
    Description: Secrets Manager SecretId/ARN containing the OIDC data
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for csci-e-11.org (e.g., Z123ABC...)
  CertificateArn:
    Type: String
    Default: ""
    Description: "(Optional) Existing ACM certificate ARN for csci-e-11.org. Leave blank to auto-create."
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues: [CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET]
    Description: Default LOG_LEVEL environment value for the function

Conditions:
  CreateAcmCert: !Equals [!Ref CertificateArn, ""]

Resources:
  # Optional, auto-created ACM cert for the staging domain
  StagingCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: CreateAcmCert
    Properties:
      DomainName: stage.csci-e-11.org
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: stage.csci-e-11.org
          HostedZoneId: !Ref HostedZoneId

  # Staging HTTP API fronting the Lambda, bound to stage.csci-e-11.org in Route53
  StagingHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: stage
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowMethods: ['GET','POST','OPTIONS']
      Domain:
        DomainName: stage.csci-e-11.org
        CertificateArn: !If [CreateAcmCert, !Ref StagingCertificate, !Ref CertificateArn]
        Route53:
          HostedZoneId: !Ref HostedZoneId
  # Lambda function — JSON-only API (no Flask)
  E11HomeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        RequirementsFile: requirements.txt   # relative to CodeUri (src/)
    Properties:
      Runtime: python3.13
      CodeUri: src/
      Handler: home_app.home.lambda_handler
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DDB_TABLE_ARN: !Ref UsersTableArn
          OIDC_SECRET_ID: !Ref OidcSecretId
          LOG_LEVEL: !Ref LogLevel            # default; can be overridden per request JSON
          SESSIONS_TABLE_NAME: !Ref SessionsTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: UsersTableRW
              Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Ref UsersTableArn
                - !Sub "${UsersTableArn}/index/*"

            - Sid: SecretsGet
              Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref OidcSecretId

            - Sid: AllowRoute53Changes
              Effect: Allow
              Action:
                - route53:ChangeResourceRecordSets
                - route53:ListResourceRecordSets
                - route53:GetChange
              Resource: "arn:aws:route53:::hostedzone/*"

            - Sid: AllowSES
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
            - Sid: SessionsTableRW
              Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource:
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::REGION}:${AWS::AccountId}:table/${SessionsTableName}"
                - !Sub "arn:${AWS::Partition}:dynamodb:${AWS::REGION}:${AWS::AccountId}:table/${SessionsTableName}/index/*"

      Events:
        StageAnyRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref StagingHttpApi
            Path: /
            Method: ANY
            PayloadFormatVersion: "2.0"
        StageAnyProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref StagingHttpApi
            Path: /{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0"

Outputs:
  # Staging-specific outputs
  StagingApiId:
    Description: Staging HTTP API ID
    Value: !Ref StagingHttpApi
  StagingDomainUrl:
    Description: Staging base URL
    Value: "https://stage.csci-e-11.org/"
  HomeFunction:
    Description: Home Lambda function name
    Value: !Ref E11HomeFunction
  HostedZoneId:
    Description: Route53 Hosted Zone
    Value: !Ref HostedZoneId
