name: CI for lambda-home
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    env:
      AWS_DEFAULT_REGION: 'localhost'
      AWS_ENDPOINT_URL: 'http://localhost:8000'
      AWS_ACCESS_KEY_ID: 'minioadmin'
      AWS_SECRET_ACCESS_KEY: 'minioadmin'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          cd etc/e11-cli/lambda-home
          make install
          make lint
