name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e11
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up pipx
        run: |
          sudo apt -y update
          sudo apt -y install pipx
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.in-project true

      - name: Install e11 deps with Poetry
        run: |
          cd spring26/etc/e11
          pwd
          poetry install --sync

      - name: Run tests with coverage
        run: |
          pwd
          poetry run make pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: e11/coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}  # not needed for public repos
