name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e11
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.11", "3.10" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true   # creates .venv in repo (your preference)
          installer-parallel: true

      - name: Install deps with Poetry
        run: poetry install --sync

      - name: Run tests with coverage
        run: poetry run make pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: e11/coverage.xml
          flags: unittests
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}  # not needed for public repos
